FROM node:22-alpine
WORKDIR /app
COPY astro.config.mjs astro-i18next.config.mts tsconfig.json tailwind.config.mjs package.json pnpm-lock.yaml ./
RUN npm i -g pnpm
RUN pnpm install
COPY . .
EXPOSE 4321
CMD [ "pnpm", "dev", "--host"]