services:
  astro-portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development